Repository LEAP-2025-J/team-3-qr-menu, pull requests merged in 2025-08, with the labels that each got.

#120 production deploy done
  frontend/.env.vercel
  frontend/app/admin/qr-codes/page.tsx
  frontend/config/api.ts
Labels: documentation

#121 Ui zasaj oorchilson
  .DS_Store
  frontend/app/page.tsx
  frontend/components/qr-menu/discount-banner.tsx
  frontend/components/qr-menu/header.tsx
  frontend/components/qr-menu/menu-grid.tsx
  frontend/components/ui/toast.tsx
Labels: documentation

#125 admin order logic added
  backend/controllers/order.controller.ts
  backend/controllers/reservation.controller.ts
  backend/controllers/table.controller.ts
  backend/models/model.table.ts
  frontend/app/admin/page.tsx
  frontend/app/admin/qr-codes/page.tsx
  frontend/app/page.tsx
  frontend/components/admin/admin-dashboard.tsx
  frontend/components/admin/admin-header.tsx
  frontend/components/admin/orders/dashboard-stats.tsx
  frontend/components/admin/orders/order-tab.tsx
  frontend/components/admin/orders/reservation-tab.tsx
  frontend/components/admin/orders/table-card.tsx
  frontend/components/admin/orders/table-grid-left.tsx
  frontend/components/admin/orders/table-grid-right.tsx
  frontend/components/admin/orders/table-header.tsx
  frontend/components/admin/orders/table-layout.tsx
  frontend/components/admin/orders/table-stats-cards.tsx
  frontend/components/admin/orders/table-utils.ts
  frontend/components/admin/orders/tables-grid.tsx
  frontend/components/admin/types/table-layout.type.ts
  frontend/components/admin/types/table-types.ts
  frontend/components/admin/types/tables-grid.type.ts
  frontend/components/admin/utils/date-utils.ts
  frontend/components/admin/utils/order-utils.ts
  frontend/components/ui/toast.tsx
  frontend/config/api.ts
  frontend/contexts/notification-context.tsx
  frontend/hooks/use-admin-data.ts
  frontend/hooks/use-table.ts
Labels: enhancement

#129 bug zasaw
  backend/controllers/reservation.controller.ts
  backend/controllers/table.controller.ts
  backend/models/model.order.ts
  frontend/.env.vercel
  frontend/app/globals.css
  frontend/app/page.tsx
  frontend/components/admin/admin-dashboard.tsx
  frontend/components/admin/menu/category-modal.tsx
  frontend/components/admin/menu/menu-card.tsx
  frontend/components/admin/menu/menu-modal.tsx
  frontend/components/admin/orders/create-order-modal.tsx
  frontend/components/admin/orders/edit-reservation-modal-new.tsx
  frontend/components/admin/orders/edit-reservation-modal.tsx
  frontend/components/admin/orders/order-tab.tsx
  frontend/components/admin/orders/orders-list.tsx
  frontend/components/admin/orders/print-modal.tsx
  frontend/components/admin/orders/reservation-modal.tsx
  frontend/components/admin/orders/reservation-tab.tsx
  frontend/components/admin/orders/table-card.tsx
  frontend/components/admin/orders/table-grid-left.tsx
  frontend/components/admin/orders/table-grid-right.tsx
  frontend/components/admin/orders/table-layout.tsx
  frontend/components/admin/orders/table-list-view.tsx
  frontend/components/admin/orders/table-stats-cards.tsx
  frontend/components/admin/orders/table-utils.ts
  frontend/components/admin/orders/tables-grid.tsx
  frontend/components/admin/orders/total-orders-modal.tsx
  frontend/components/admin/types/table-types.ts
  frontend/components/admin/types/tables-grid.type.ts
  frontend/components/admin/utils/index.ts
  frontend/components/admin/utils/order-utils.ts
  frontend/components/admin/utils/price-utils.ts
  frontend/components/qr-menu/cart-modal.tsx
  frontend/components/qr-menu/menu-grid.tsx
  frontend/config/api.ts
  frontend/next.config.mjs
  frontend/package.json
  frontend/tailwind.config.js
Labels: bug

#133 undsen hel mongol bolgoson, footerin heliig bas ynzalsan
  frontend/app/layout.tsx
  frontend/components/qr-menu/footer.tsx
  frontend/contexts/language-context.tsx
Labels: documentation

#149 notification system updated
  backend/controllers/discount.controller.ts
  backend/controllers/menu.controller.ts
  backend/controllers/order.controller.ts
  backend/controllers/reservation.controller.ts
  backend/controllers/table.controller.ts
  backend/models/model.discount.ts
  backend/models/model.order.ts
  backend/routes/discount.routes.ts
  backend/scripts/migrate-business-day.ts
  backend/scripts/migrate-order-source.js
  backend/scripts/migrate-order-source.ts
  backend/scripts/seed-discount.js
  backend/scripts/test-business-day.ts
  backend/server.ts
  backend/utils/business-day-utils.ts
  frontend/app/page.tsx
  frontend/components/admin/admin-dashboard.tsx
  frontend/components/admin/admin-header.tsx
  frontend/components/admin/menu/menu-management.tsx
  frontend/components/admin/notifications/notification-dialog.tsx
  frontend/components/admin/orders/create-order-modal.tsx
  frontend/components/admin/orders/order-history.tsx
  frontend/components/admin/orders/order-tab.tsx
  frontend/components/admin/orders/orders-list.tsx
  frontend/components/admin/orders/recent-orders.tsx
  frontend/components/admin/orders/table-card.tsx
  frontend/components/admin/orders/table-list-view.tsx
  frontend/components/admin/orders/table-utils.ts
  frontend/components/admin/orders/tables-grid-utils.ts
  frontend/components/admin/orders/total-orders-modal.tsx
  frontend/components/admin/settings/business-day-settings.tsx
  frontend/components/admin/settings/discount-settings.tsx
  frontend/components/admin/settings/index.ts
  frontend/components/admin/settings/settings-form.tsx
  frontend/components/admin/user-dashboard.tsx
  frontend/components/admin/utils/order-utils.ts
  frontend/components/admin/utils/print-utils.ts
  frontend/components/qr-menu/discount-banner.tsx
  frontend/components/qr-menu/footer.tsx
  frontend/components/qr-menu/header.tsx
  frontend/contexts/notification-context.tsx
  frontend/hooks/use-admin-data.ts
  frontend/hooks/use-business-day.ts
  frontend/hooks/use-discount.ts
  frontend/hooks/use-restaurant.ts
  frontend/next-env.d.ts
Labels: bug

#151 settings UI update
  frontend/components/admin/settings/business-day-settings.tsx
  frontend/components/admin/settings/discount-settings.tsx
  frontend/components/admin/settings/settings-form.tsx
  frontend/hooks/use-discount.ts
Labels: enhancement
